{% set name = "imagecodecs" %}
{% set version = "2024.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fde46bd698d008255deef5411c59b35c0e875295e835bf6079f7e2ab22f216eb
  patches:              # [unix and not ppc64le]
    - allow_jxl.patch   # [unix and not ppc64le]

build:
  number: 6
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - numpy
    - cython
    - zlib
    - bzip2
    - xz
    - zstd
    - lz4-c
    - libpng
    - libwebp
    - jxrlib
    - libjpeg-turbo
    - giflib
    - openjpeg
    # hmaarrfk - 2024/03/06
    # I have compilation errors on windows (I think it is due to the fact that the libraries are statically linked)
    # https://github.com/conda-forge/libjxl-split-feedstock/issues/19
    # And ppc64le has ICE errors for libjxl
    # https://github.com/conda-forge/libjxl-split-feedstock/issues/20
    - libjxl  # [unix and not ppc64le]
    - blosc
    - c-blosc2
    - lcms2
    - libaec
    - brotli
    - libzopfli
    - charls
    - snappy
    - libtiff
    - libavif
    - lerc
    - zfp
    - libdeflate
    - brunsli   # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}


test:
# Running the full test suite adds about 17 MB of files...
{% if false %}
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - cd tests
    # 20210717 hmaarrfk: This test seems to be flaky in the upstream
    # test procedure
    # https://github.com/conda-forge/imagecodecs-feedstock/pull/32#issuecomment-863041029
    - python test_imagecodecs.py -k "not test_image_roundtrips[jpeg2k-uint16-rgb-out-bytearray-None]"
{% endif %}
  imports:
    - imagecodecs
    - imagecodecs._imagecodecs

about:
  home: https://www.lfd.uci.edu/~gohlke/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - 3rdparty/liblzf/LICENSE
    - 3rdparty/bitshuffle/LICENSE
    - 3rdparty/openjpeg/LICENSE
  summary: Image transformation, compression, and decompression codecs
  description: |
    The imagecodecs package provides various block-oriented, in-memory buffer
    transformation, compression, and decompression functions for use in the
    tifffile, czifile, and other Python imaging modules.

    Decode and/or encode functions are currently implemented for Zlib DEFLATE,
    ZStandard, Blosc, LZMA, BZ2, LZ4, LZW, LZF, PNG, WebP, JPEG 8-bit,
    JPEG 12-bit, JPEG SOF=0xC3, JPEG 2000, JPEG XR, PackBits, Packed Integers,
    Delta, XOR Delta, Floating Point Predictor, and Bitorder reversal.

  doc_url: https://www.lfd.uci.edu/~gohlke/
  dev_url: https://github.com/cgohlke/imagecodecs

extra:
  recipe-maintainers:
    - csachs
    - hmaarrfk
    - sdvillal
