{% set version = "2024.12.30" %}

package:
  name: imagecodecs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/imagecodecs/imagecodecs-{{ version }}.tar.gz
  sha256: 4c88f745719313cabea6dd5f1e69c9f93346de91c0f1e770eb969f2232247f21

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - zlib
    - zlib-ng
    - bzip2
    - liblzma-devel
    - zstd
    - lz4-c
    - libpng
    - libwebp
    - jxrlib
    - libjpeg-turbo
    - giflib
    - openjpeg
    - libjxl
    - blosc
    - c-blosc2
    - lcms2
    - libaec
    - brotli
    - libzopfli
    - charls
    - snappy
    - libtiff
    - libavif
    - lerc
    - zfp
    - libdeflate
    - brunsli   # [not win]
  run:
    - python


test:
# Running the full test suite adds about 17 MB of files...
{% if false %}
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - cd tests
    # 20210717 hmaarrfk: This test seems to be flaky in the upstream
    # test procedure
    # https://github.com/conda-forge/imagecodecs-feedstock/pull/32#issuecomment-863041029
    - python test_imagecodecs.py -k "not test_image_roundtrips[jpeg2k-uint16-rgb-out-bytearray-None]"
{% endif %}
  commands:
# Just a subset of the codecs so I can feel like the test works. Add more as needed
{% set expected_codecs = ["BLOSC", "BLOSC2", "ZSTD", "LZ4", "ZLIB", "ZLIBNG", "LZMA", "JPEGXL"] %}
{% for codec in expected_codecs %}
    - echo "Testing for {{ codec }}"
    - python -c "import imagecodecs; assert imagecodecs.{{ codec }}.available"
{% endfor %}
  imports:
    - imagecodecs
    - imagecodecs._imagecodecs

about:
  home: https://www.lfd.uci.edu/~gohlke/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - 3rdparty/liblzf/LICENSE
    - 3rdparty/bitshuffle/LICENSE
    - 3rdparty/openjpeg/LICENSE
  summary: Image transformation, compression, and decompression codecs
  description: |
    The imagecodecs package provides various block-oriented, in-memory buffer
    transformation, compression, and decompression functions for use in the
    tifffile, czifile, and other Python imaging modules.

    Decode and/or encode functions are currently implemented for Zlib DEFLATE,
    ZStandard, Blosc, LZMA, BZ2, LZ4, LZW, LZF, PNG, WebP, JPEG 8-bit,
    JPEG 12-bit, JPEG SOF=0xC3, JPEG 2000, JPEG XR, PackBits, Packed Integers,
    Delta, XOR Delta, Floating Point Predictor, and Bitorder reversal.

  doc_url: https://www.lfd.uci.edu/~gohlke/
  dev_url: https://github.com/cgohlke/imagecodecs

extra:
  recipe-maintainers:
    - csachs
    - hmaarrfk
    - sdvillal
    - traversaro
